version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka-data:/var/lib/kafka/data  # <-- Persist Kafka data
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  
  flask-app:
    build: ./modules/mbapi
    environment:
      KAFKA_SERVER: "kafka:9092"
      DB_USERNAME: "ct_admin"
      DB_NAME: "geoconnections"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      - kafka
volumes:
  kafka-data:  # This defines a Docker volume for persistence